### ISSUE TITLE
Data for 'Working in Python with Hadoop Streaming" example 

### ISSUE THREAD

**Issue by mgeorgy** [bbengfort/hadoop-fundamentals#1]
Hello.  I'm working through the video series and it doesn't appear that the data from this section (flight delay information) is included in the repo.  Is it available elsewhere?

Thank you.

**Comment by spaztic1215** [comment]
Hi!  All the data sets should be in a compressed format in the data folder:

https://github.com/bbengfort/hadoop-fundamentals/tree/master/data

So you will have to unzip or uncompress them to use them.

i.e. - unzip hadoop-fundamentals/data/flight_data.zip

**Comment by mgeorgy** [comment]
Hi.  Thanks.  I did that, but the contents of the archive do not match Ben's demo.  His demo includes files of the format flights-<month>2014.csv.  The flight_data archive includes:

flight_data/airlines.tsv
flight_data/cancellation_reasons.tsv
flight_data/carriers.tsv
flight_data/ontime_flights.tsv
flight_data/README.md

**Comment by spaztic1215** [comment]
This is unfortunate confusing naming (it even confused me) of our data sets, because we use the ontime-flight data set in different formats in our videos.  I believe Ben's demo is referring to the data in ontime.zip:

ontime/README.md
ontime/airlines.csv
ontime/airports.csv
ontime/flights.csv

Although you may have to update the filename in the code b/c the CSV is just named flights.csv.  If this is still not the right data, can you tell me which specific video (and running time) you need data for?  We'll ask the O'Reilly team to add some notes to the specific data sets referenced.  Thanks!

**Comment by mgeorgy** [comment]
Thanks again.  I'm reviewing 'Working in Python with Hadoop Streaming' @4:56.  Ben provides the directly link to the flight_data.zip archive you suggested (https://github.com/bbengfort/hadoop-fundamentals/blob/master/data/flight_data.zip).  Unfortunately, the file he uses (as viewed in Sublime) doesn't match any of the files, or file formats, in the archive.

**Comment by spaztic1215** [comment]
Thanks for this catch, I went back to the video and this is one of the few cases (possibly only instance) where we actually reference a data set that is not in this repo.  This data can be downloaded from the Bureau of Transportation Statistics website: http://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236

If you select April 2014 as the Filter Period, and then select the "Prezipped File" option, you can download a zipped version of the CSV (although it should also work if you want to use the latest data available).

I think what happened is that we wanted to include this data but it was way too large.  But I'll let O'Reilly Media know to put a link to the data download instructions.

**Comment by mgeorgy** [comment]
Perfect.  Thank you.
