### ISSUE TITLE
#cat flights.csv | ./mapper.py | sort | ./reducer.py  Error: "No such file or directory 

### ISSUE THREAD

**Issue by JoaoPauloSousaCoelho** [bbengfort/hadoop-fundamentals#17]
Hi,

Please could you help me to deal with this error?

This message is sent every time that I try to execute the command: cat flights.csv | ./mapper.py | sort | ./reducer.py.  I want to highlight that the files flights.csv, mapper.py and reducer.py are in the same directory and I've already altered the permission of mapper.py and reducer.py files through the execution of the commands "chmod +x". Attached to this email, you can find the image of Cloudera Terminal (I' m using C
<img width="387" alt="Error - Example" src="https://user-images.githubusercontent.com/59370657/75158149-48b43500-56f4-11ea-9f5a-a4c279d018b1.PNG">
loudera QuickStart)

Best regards.

João Paulo

**Comment by bbengfort** [comment]
Hi @JoaoPauloSousaCoelho I'm sorry, I'm not sure what to tell you about this - are you using bash? It looks like perhaps the mapper and reducer aren't able to read from stdin? Or it might not be related to the mapper and reducer at all. Perhaps try saving the intermediate output for each file one at a time rather than using pipe?
