### ISSUE TITLE
"Linear Regressions" example

### ISSUE THREAD

**Issue by perryhook** [bbengfort/hadoop-fundamentals#2]
Hi,

I ran into a couple problems trying to run the map reduce example on the wine quality dataset. I should note I'm using the Hortonworks Hadoop distribution, but I'm pretty sure at least one of the problems is unrelated to that.
#### csv headers

First, both csv files in the dataset have column headers that cause the mapper to fail. I don't think there's a way to ignore the headers using Python's default csv reader, AFAIK. Running the example without Hadoop will demonstrate the problem:

`$ cat winequality-red.csv | ./mapper.py | sort | ./reducer.py`
`Traceback (most recent call last):
  File "./mapper.py", line 52, in <module>
    mapper.map()
  File "./mapper.py", line 42, in map
    for wine in self:
  File "./mapper.py", line 47, in __iter__
    for wine in map(parse, reader):
  File "./mapper.py", line 24, in parse
    return dict(zip(fields, [float(item) for item in row]))
ValueError: invalid literal for float(): fixed acidity`

The fix is easy, just delete the first line of winequality-red.csv and winequality-white.csv before putting them in HDFS.
#### providing supplemental files

The second problem I have is that the command to run the map reduce job on Hadoop does not work for me. An earlier example in the series that uses the Streaming API worked fine with Hortonworks, but when supplemental files (like `framework.py` and `theta.json`) need to be provided it fails. So when I do:

`$ hadoop jar $HADOOP_STREAMING -input wines -output sse -mapper mapper.py -reducer reducer.py -file ./mapper.py -file ./reducer.py -file ./framework.py -file theta.json`

I get errors that look like this for each mapping task:
`15/12/02 01:37:21 INFO mapreduce.Job: Task Id : attempt_1449010601094_0012_m_000002_0, Status : FAILED
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:322)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:535)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:453)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)`

This didn't really help me figure out what was going wrong, but after a bunch of experimentation and close reading of the docs, I found that this will work, _if you are in the_ `hadoop-fundamentals` _directory_ (parent of `wines`):

`$ hadoop jar $HADOOP_STREAMING -files wines -input wines -output sse -mapper wines/mapper.py -reducer wines/reducer.py -file wines/framework.py -file wines/theta.json`

Does anyone else run into this issue?

**Comment by bbengfort** [comment]
@perryhook thanks for taking the time to comment - we definitely appreciate feedback. Just one general comment before we dig into specifics; it does help if we have a pointer to where you are attempting to run the example. This code is both for a book, a video, and a course; perhaps we accidentally changed the repo without thinking about an example. Now onto specifics:
1. For the CSV data set - you're right, simply removing the header takes care of the problem. I thought we had removed it, but I guess it stuck. My preferred fix for dealing with these issues is instead of changing the data, wrap your float parsing in a try/except block. In a big data context, there could be a .001% error rate - but that's still a huge number of data errors! Ignoring the header row, or even that small number of errors is usually not a problem. Just a best practice kind of thing. 
2. That's really odd about the paths to Hadoop Streaming; if you're providing good paths it should work - I've never encountered that before. Perhaps your version of Hadoop has finally deprecated the `-file` option in favor of `-files` (which has been warned about for a while) - and the reason it worked in the second example was because you used `-files`?

**Comment by perryhook** [comment]
@bbengfort Ah, sorry I didn't realize the code was used in multiple places. I'm watching the video series.
1. Excellent suggestion about using a try/except block, I like that approach better too. Thanks!
2. The Hadoop version I have is 2.7.1.2.3.2.0-2950, and also wondered if `-file` was deprecated because of the warnings. I never was able to get `-files` to work using the syntax the warning and Hadoop docs suggest (comma separated list), came across [this stack overflow post](http://stackoverflow.com/questions/26812124/hadoop-streaming-with-multiple-python-files), and played around with it until it worked. Note that `-files` also has to be provided as the first option, since it is a ['generic command option'](https://hadoop.apache.org/docs/r1.2.1/streaming.html#Generic+Command+Options). There's probably a more correct incantation of the command that I didn't stumble upon.

I hope this helps someone in the future. Thanks for your advice, and a great video series!
